### ISSUE TITLE
What to do with feedback

### ISSUE THREAD

**Issue by syonip** [ueman/feedback#10]
Hi,
This looks like a cool plugin!
I couldn't figure out how the user should actually send the feedback.
Thanks.

**Comment by ueman** [comment]
That is up to you. You just have to implement the onFeedback-callback as shown below:
```dart
import 'dart:typed_data';

import 'package:feedback/feedback.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(
    BetterFeedback(
      child: MyApp(
        key: GlobalKey(debugLabel: 'app_key'),
      ),
      onFeedback: (
        BuildContext context,
        String feedbackText,
        Uint8List feedbackScreenshot,
      ) {
        // TODO: upload to your server, share via email...
      },
    ),
  );
}
```
And somewhere in your code you have to call `BetterFeedback.of(context).show();` to show the feedback view.

**Comment by syonip** [comment]
Great thanks!
I would be good to include this piece of code in the main readme page.
I can make a PR if you want.

**Comment by ueman** [comment]
Well, it is already included in the readme albeit with a sample function. You don't need to make a PR. More and better documentation is already on my todo list.

**Comment by syonip** [comment]
Cool, thanks for making this :)
