### ISSUE TITLE
Screenshot doesn't show google map

### ISSUE THREAD

**Issue by syonip** [ueman/feedback#11]
I'm using the google maps plugin in my app, and the generated screenshot doesn't include the map.
Screenshots included.

![Screenshot_1584089943](https://user-images.githubusercontent.com/5416329/76606141-6ec23d80-651a-11ea-9071-dbd8f60ff3e9.png)
![screenshot](https://user-images.githubusercontent.com/5416329/76606168-78e43c00-651a-11ea-9677-f96ccfb628d8.png)

**Comment by ueman** [comment]
Is the Google Maps Plugin using platform views? I haven't tested it yet with platform views but I'm guessing it doesn't work with them as it only uses pure Dart and Flutter APIs to create the screenshot.

**Comment by syonip** [comment]
Yes it seems that it does use platform views.

**Comment by syonip** [comment]
I've noticed they just added a `takeSnapshot()` method to the maps plugin, maybe that can help: https://github.com/flutter/plugins/commit/03182d26309a05f483b58d6c5f29946e066c94f5

**Comment by ueman** [comment]
Unfortunately it is out of scope to add workarounds on a per library basis.
This is also a known issue of Flutter, see:
- https://github.com/flutter/flutter/issues/25306
- https://github.com/flutter/flutter/issues/23435

**Comment by shivamagarwal2097** [comment]
same issue show in apple map

**Comment by shivamagarwal2097** [comment]
> flutter/plugins@03182d2

anyone explain this i also get screenshot in apple map

**Comment by ueman** [comment]
Unfortunately this does not help. This functionality needs to be available for RepaintBoundaries. If you really need this functionality, you have to build it yourself. Sorry :(

**Comment by ueman** [comment]
It hasn't actually been fixed. But this library doesn't need any code changes to make it work when it gets actually implemented
