### ISSUE TITLE
Back button in draw mode should close feedback

### ISSUE THREAD

**Issue by JamesCullum** [ueman/feedback#116]
**Is your feature request related to a problem? Please describe.**
A user reported that he finds it weird that when he opens the feedback view and clicks the back button, the app follows the button. The expected reaction should be the closure of the tool, not navigating in the app.

**Describe the solution you'd like**
In draw mode a click of the back button should close the feedback view.

**Describe alternatives you've considered**
It would be possible to capture all back button clicks and make it configurable, but its closer to the expected event if this happens automatically in draw mode

**Additional context**
None

**Comment by ueman** [comment]
I think it depends on wether the user is in draw or navigation mode like you said. I can see how that can be confusing. Thanks for bringing that up.

**Comment by ueman** [comment]
Do you think it would make sense, that the back button should undo the last draw action, or just always close the feedback dialog?

**Comment by JamesCullum** [comment]
Thats a good question - I think users expect it to first undo the last drawing and then close the feedback?
Basically equaling an "go to previous step" button.

**Comment by ueman** [comment]
This is now available in https://pub.dev/packages/feedback/versions/2.1.0-beta

**Comment by Zazo032** [comment]
Should the back button on navigation mode also close the Feedback tool if the current route is the first one? (going back will close the app while the tool is open)

**Comment by JamesCullum** [comment]
That's a good question - what do you think? Would agree that this makes sense.
