### ISSUE TITLE
Sidebar becomes visible when you shrink the width of the window

### ISSUE THREAD

**Issue by zambetpentru** [ueman/feedback#118]
Hi,

Somehow the sidebar becomes visible when you shrink the width of the Window?

![image](https://user-images.githubusercontent.com/81489824/132234865-7765088b-7498-427c-a733-1b2a3a351dfc.png)

**Comment by ueman** [comment]
Yeah, I already noticed it, too. Are you open to fix it in a PR?

**Comment by zambetpentru** [comment]
Greetings, one of these day when I find time I'll figure out how to do a pull request but for now:

A fix can be to modify https://github.com/ueman/feedback/blob/master/lib/src/feedback_widget.dart and add a new line 155

     **if (widget.isFeedbackVisible)**
                Align(
                  alignment: Alignment(
                    controlsHorizontalAlignment.value,
                    -0.7,
                  ),
                  child: ControlsColumn(
                    mode: mode,
                    activeColor: painterController.drawColor,
                    colors: widget.drawColors,
                    onColorChanged: (color) {
                      setState(() {
                        painterController.drawColor = color;
                      });
                      _hideKeyboard(context);
                    },
