### ISSUE TITLE
Feature request: Flexibility on question(s) presented to user?

### ISSUE THREAD

**Issue by seanmc86** [ueman/feedback#12]
Hi @ueman - thank you for this package, it is certainly interesting and could be helpful to my project in the near future.

For me to justify using it, I would need some flexibility around the questions presented to the user. Instead of a fixed "What's wrong?", potentially something like a supplied list of question strings that then create a new header/text entry section within a scroller (as of course space will be an issue) for each, and the output then being a list of string answers rather than a single string.

Is this something easily achievable? Would you need PR contributions?

**Comment by ueman** [comment]
The easiest solution would be to just use a custom translation. However you wouldn't be able to customize the layout.

Another solution would be to add a buttom wich opens a dialog/alert of some sort. The dialog would then be fully customizable by the consumer of this library.

**Comment by seanmc86** [comment]
The custom translation does indeed point give some flexibility to the direction the user is guided. I will consider using this as an interim solution, thanks.

I think the ability to customise the submission modal as you suggest would be very useful.

**Comment by ueman** [comment]
If you would like to work on it, I could provide some guidance and review your code.

**Comment by wilson-christian** [comment]
> The easiest solution would be to just use a custom translation. However you wouldn't be able to customize the layout.
> 
> Another solution would be to add a buttom wich opens a dialog/alert of some sort. The dialog would then be fully customizable by the consumer of this library.

Hey @ueman can you please elaborate or point me to the correct guide/example which shows how to add custom translation. I simply want to change `What's wrong?` string to `Please provide your feedback.`.

**Comment by ueman** [comment]
I've recently updated the readme with steps on how to do that. Please follow them and if you still have any question, please describe in detail what those problems are.

**Comment by wilson-christian** [comment]
Thank you for the prompt response, will take a look at readme.
