### ISSUE TITLE
`supportedLocales` is ignored

### ISSUE THREAD

**Issue by Zazo032** [ueman/feedback#122]
If you place `BetterFeedback` widget as a child of `MaterialApp`, and you define a list of supported locales like this:
```dart
supportedLocales: const <Locale>[
  Locale('de'),
  if (!kReleaseMode) Locale('en'),
],
```
it will also use `en` locale.
```dart
MaterialApp(
  builder: (BuildContext context, Widget? child) {
    return BetterFeedback(
      localizationsDelegates: const <LocalizationsDelegate>[
        AppLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
      ],
      feedbackBuilder: (BuildContext context, OnSubmit onSubmit) {
        return ...;
      },
      child: ...,
    );
  },
),
```
In this code, `AppLocalizations` supports both `de` and `en` as locales, but only `de` should be supported in release builds. However, by setting the `localizationsDelegates` param in the `BetterFeedback` widget, `supportedLocales` is ignored. If `localizationsDelegates` is not provided, an error appears when trying to call `AppLocalizations.of(context)`. Placing `BetterFeedback` as `MaterialApp`'s parent is not an option due to #120.

**Comment by ueman** [comment]
This is a use case which is not really supported as `BetterFeedback` should be wrapped around the `MaterialApp`.
