### ISSUE TITLE
Renderflex overflowed in landscape mode

### ISSUE THREAD

**Issue by ronba** [ueman/feedback#133]
### Version

2.2.0+4 - main

### Library

feedback

### Flutter channel

stable

### Flutter version

2.5.3

### Platform

Android

### Details

When using BetterFeedback in landscape mode, the following exception is thrown:

```
════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 105 pixels on the bottom.

The relevant error-causing widget was
BetterFeedback
lib/main.dart:36
...
```

### Steps to reproduce

- Clone the feedback repository.
- Open feedback/feedback/example/main.dart
- Add the following code as the first item of the [column](https://github.com/ueman/feedback/blob/fb0938ba0d0d85a1ccc5855a9d42a4b0415d9487/feedback/example/lib/main.dart#L95):
```dart
Row(
  children: [
    ElevatedButton(
        onPressed: () {
          SystemChrome.setPreferredOrientations([
            DeviceOrientation.portraitDown,
            DeviceOrientation.portraitUp
          ]);
        },
        child: const Text('portrait')),
    ElevatedButton(
        onPressed: () {
          SystemChrome.setPreferredOrientations([
            DeviceOrientation.landscapeLeft,
          ]);
        },
        child: const Text('landscape')),
  ],
),
```
- Start main.dart in the android emulator, I'm using a Pixel_3a_API_31
- Click on the landscape button

Result:
```
════════ Exception caught by rendering library ═════════════════════════════════
The following assertion was thrown during layout:
A RenderFlex overflowed by 105 pixels on the bottom.

The relevant error-causing widget was
BetterFeedback
lib/main.dart:36
```

# Debugging:

The offending code is [this](https://github.com/ueman/feedback/blob/cdbe71a7231a5a6be1cb0da6bc6cefa8994ce99b/feedback/lib/src/controls_column.dart#L95).

By wrapping the buttons with an Expanded widget, the error goes away, but some of the buttons remain invisible:

```dart
for (final color in colors)
Expanded(
  child: _ColorSelectionIconButton(
    key: ValueKey<Color>(color),
    color: color,
    onPressed: isNavigatingActive ? null : onColorChanged,
    isActive: activeColor == color,
  ),
)
```

![image](https://user-images.githubusercontent.com/10216856/139615548-318ad5ff-5d14-4987-acb6-483509c5e81a.png)

**Comment by caseycrogers** [comment]
This should be alleviated significantly by #147 - the controls column will wrap instead of overflowing.
