### ISSUE TITLE
Custom localizationsDelegates doesn't work

### ISSUE THREAD

**Issue by tolik505** [ueman/feedback#134]
### Version

2.2.0+4

### Library

feedback

### Flutter channel

stable

### Flutter version

2.5.3

### Platform

iOS

### Details

Hi. I tried to use different languages for the  widget but it didn't work.

I believe it's happening because of the merge of delegates https://github.com/ueman/feedback/blob/master/feedback/lib/src/l18n/localization.dart#L31

`GlobalFeedbackLocalizationsDelegate ` is always present in the final array of delegates and used for checking of supported languages. I believe if client provides an array of delegates it shouldn't be merged.

Does my assumption make sense?

Thanks!

### Steps to reproduce

1. Create custom localisation delegate with supported languages
`static final _supportedLocales = <Locale, FeedbackLocalizations>{
    const Locale('en'): const EnFeedbackLocalizations(),
    const Locale('es'): const EsFeedbackLocalizations(),
  };`
2. Use it in localizationsDelegates property of BetterFeedback widget.
3. Set `localeOverride: Locale('es')`
4. Run app and see log `The locale es is not supported, falling back to englisch translations`

**Comment by ueman** [comment]
Thanks for the report. From what you're describing it seems you're right. I'll have to look into it.

**Comment by tolik505** [comment]
Sorry, my bad. I didn't extend FeedbackLocalizations by custom translation. Now it works. Thanks!
