### ISSUE TITLE
Clipboard does not work correctly

### ISSUE THREAD

**Issue by ueman** [ueman/feedback#138]
Currently, the clipboard does work correctly in the feedback bottom sheet.
This can be fixed by changing [this line](https://github.com/ueman/feedback/blob/65052da7e316d4cc41ccb1d6b58b3dbaea7b718d/feedback/lib/src/feedback_widget.dart#L205) to, for example, `0.7`. 

This kinda makes me think that this is caused by the [Navigator](https://github.com/ueman/feedback/blob/65052da7e316d4cc41ccb1d6b58b3dbaea7b718d/feedback/lib/src/feedback_bottom_sheet.dart#L26) being bigger than the clickable/touchable area of the bottom sheet. Thus, the clipboard menu can be placed where it can't be clicked.

**Comment by ueman** [comment]
After investigating some more, I think this is an issue with the way the navigator is used.
If the navigator covers the whole screen, the clipboard works as expected. However, the navigator doesn't allow click through, which makes it impossible to anything else than the bottom sheet.

**Comment by diegoveloper** [comment]
@ueman did you report this issue on the Flutter repo?, maybe the could help :D

**Comment by ueman** [comment]
@diegoveloper Not yet, but I'll try to create a simple example which reproduces this. In the meantime, I think I have solution, but I need to test it, to be sure that I don't break anything else :D

**Comment by ueman** [comment]
Moving the usage of the Navigator up the tree in the package breaks `Navigator.of(context, rootNavigator: true)` calls of users of this library but fixes the problem. Therefor, I think I shouldn't make this change. 

I'll need to create a reproducible example and create an issue in the flutter repo, so that it gets fixed there.

**Comment by ueman** [comment]
This seems to be fixed by #149

**Comment by diegoveloper** [comment]
Hello @ueman , can you add a comment here when you release a new version? (just to be notified) Thanks :D

**Comment by ueman** [comment]
I've already released it as a beta version: https://pub.dev/packages/feedback/versions/2.3.0-beta
