### ISSUE TITLE
How to clear feedback

### ISSUE THREAD

**Issue by jonmountjoy** [ueman/feedback#14]
Hello,

How do I clear the feedback, so that the next time `.show()` is invoked, it doesn't show the old text and drawing?  I saw no method at all to do this.  It could perhaps be added as an optional argument to '.hide(mustClear: true)'.

PS. This is great, thank you!

**Comment by JayPerfetto** [comment]
I had to pull this code into my own project and adapt it in order to get this to work - its a pretty simple change, but it has not yet been implemented in the package. 

In FeedbackWidget: Pass the Text Editing Controller and Paint Controller into the sendFeedback method
```
 onSubmit: (context, feedback) {
                        sendFeedback(
                          context,
                          FeedbackData.of(context).onFeedback,
                          screenshotController,
                          feedback,
                          painterController: painterController,
                          textEditingController: textEditingController,
                        );
                      }, 
```

Then in that function, clear those controllers after capturing the screenshot
```

        // Take high resolution screenshot
        final screenshot = await controller.capture(
          pixelRatio: 3,
          delay: const Duration(milliseconds: 0),
        );

        painterController.clear();
        textEditingController.clear();
```

**Comment by seanradford** [comment]
Another nicety might be a button to clear the contents of the text field. (Similar to the trash can to delete any annotations).

**Comment by ueman** [comment]
This is fixed in [this beta](https://pub.dev/packages/feedback/versions/1.0.0-beta) and thus also in the [nullsafety prerelease](https://pub.dev/packages/feedback/versions/1.0.0-nullsafety).
