### ISSUE TITLE
Leverage DraggableScrollabeController Once It's Available

### ISSUE THREAD

**Issue by caseycrogers** [ueman/feedback#150]
When #149 goes in, developers using the expandable bottom sheet feature will have to use `FeedbackSheetDragHandle` in the feedback sheet builder to provide a visual drag handle for users.

This is pretty clunky, but the only way to do it because the drag handle needs to be placed as a fixed header on top of their scrollable widget in order for users to be able to click and drag on it to drag the sheet. Once `DraggableScrollableSheet` supports programmatic control in production (see: https://github.com/flutter/flutter/pull/92440) we can pull the drag handle out of the builder so that developers don't have to provide it.

Additionally, the `feedback_widget` uses a value notifier internally to manage sheet related animations. This can also be replaced by referencing the controller directly assuming the controller is made a `ChangeNotifier`.

**Comment by kamami** [comment]
Any updates to this?

**Comment by ueman** [comment]
DraggableScrollabeController will probably be included in the next Flutter version. There's no date for that yet, but I expect it to be around February or March.

**Comment by kamami** [comment]
Is already on `master` and full functional?

**Comment by ueman** [comment]
I'm not sure what you're referring to. flutter/flutter#92440 is already on master and fully functional. This library however doesn't yet support it.

**Comment by kamami** [comment]
Thanks for your response! I missed that this is a separate package...

**Comment by quoc-huynh-cosee** [comment]
Any updates on this?

**Comment by ueman** [comment]
Closed via https://github.com/ueman/feedback/pull/239
