### ISSUE TITLE
Add Russian and Ukrainian localizations

### ISSUE THREAD

**Issue by volodymyrd** [ueman/feedback#155]
I'd like to create localization for Russian and Ukrainian languages. I've created a feature branch with my changes, but cannot submit them. Please provide the way how to contribute here, thanks

**Comment by ueman** [comment]
Hey, thanks! You can read how to create a pull request [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).
