### ISSUE TITLE
Upload to feedback to sentry and attach to exceptions

### ISSUE THREAD

**Issue by sils** [ueman/feedback#168]
**Is your feature request related to a problem? Please describe.**
We want to use feedback to get feedback whenever an uncatched exception gets thrown. Right now we can't link the feedback to sentry exceptions.

**Describe the solution you'd like**
Give us a parameter for showAndUploadToSentry of type SentryId so that it can get linked.

**Describe alternatives you've considered**
Forking/reimplementing feedback-sentry

**Additional context**
-

**Comment by ueman** [comment]
Are you interested in contributing this feature?

**Comment by sils** [comment]
@ueman I don't have too much time but I hacked together https://github.com/ueman/feedback/pull/170 real quick which might work ^^

**Comment by ueman** [comment]
Just released the new version: https://pub.dev/packages/feedback_sentry/changelog
