### ISSUE TITLE
Textfield for contact details

### ISSUE THREAD

**Issue by skyface753** [ueman/feedback#176]
**Is your feature request related to a problem? Please describe.**
The Feedback (e.g. Sentry) doesn't provide a way to contact the user.

**Describe the solution you'd like**
I would like to have another Textfield where the user can fill out with contact details (e.g. mail or phone)

**Describe alternatives you've considered**
The text field could be displayed directly below or in an alert box

**Additional context**

**Comment by ueman** [comment]
This is already possible by using your own feedback builder. See the example app for inspiration.
