### ISSUE TITLE
Black Screen and cant backspace using textfield

### ISSUE THREAD

**Issue by DragonSlayer88** [ueman/feedback#177]
### Version

2.4.0

### Library

feedback

### Flutter channel

stable

### Flutter version

2.8.1

### Platform

Windows

### Details

I updated to 2.4.0 and now there is a required scrollController to pass into my customfeedbackbuilder. Now when I get a black screen.... I tried to use the customfeedback example you provided as well and still gives me a black screen. The other version 2.0.0 was working fine for me. Besides not being able to backspace in the textfield, i thought updating would be helpful. 

### Steps to reproduce

update to 2.4.0
black screen

**Comment by ueman** [comment]
Can you post your code and some more information on how to get to the black screen?

**Comment by DragonSlayer88** [comment]
Bascially i had it working i think with version 2.0.0. And when i updated to 2.4.0 it asked me to include a scrollController. Ever since then, i cant get it to work, i see a black screen. I even tried to go back to 2.0.0 but for some reason it still asks for a scrollcontroller now. Not sure what the deal is.

**Comment by DragonSlayer88** [comment]
Bascially i had it working i think with version 2.0.0. And when i updated to 2.4.0 it asked me to include a scrollController. Ever since then, i cant get it to work, i see a black screen. I even tried to go back to 2.0.0 but for some reason it still asks for a scrollcontroller now. Not sure what the deal is.

**Comment by DragonSlayer88** [comment]
I found the issue with the black screen. I was popping before i showed the feedback screen because i have it in my drawer. SO i wanted to pop the drawer before i opened feedback. This was working fine in the older version. 

But it still remains the textfield backspace issue. Very annoying problem. Only this textfield cant backspace.

**Comment by MichaelSunday** [comment]
> 

Yeah I have the same issue with that specific textfield also. Currently trying to fix atm.

**Comment by ueman** [comment]
@MichaelSunday If you figure it out I would really appreciate reading your finding or a PR.

**Comment by DragonSlayer88** [comment]
Please look into this. I know this problem is isolated in this package somewhere.

**Comment by ueman** [comment]
> Please look into this. I know this problem is isolated in this package somewhere. 

I currently don't have time to do that, you know, life and all that.

However, I'm pretty sure it's something in Flutter itself and not specific to this package because there's nothing special about the way the textfields are used and it works on mobile and web.

If a previous version worked fine for you, I suggest reverting back to it for now. If that's the case, please let me know so I have some more information to work with when I come around to it.

**Comment by ueman** [comment]
Fixed in 2.4.1

**Comment by DragonSlayer88** [comment]
I tried 2.4.1, still did not fix the issue

**Comment by ueman** [comment]
> I tried 2.4.1, still did not fix the issue

Which Flutter version are you on?

On 2.10 I'm now able to backspace in textfields on desktop.

**Comment by DragonSlayer88** [comment]
Sorry yes, Flutter 2.1.0 came out yesterday. I upgraded to that and now it works. Thank you for the continued support. I appreciate it. Well done.
