### ISSUE TITLE
Theme change

### ISSUE THREAD

**Issue by mukireus** [ueman/feedback#19]
Hi,

Firstly, thank you for this package.

My existing theme changed when I added this package to my project.

How can i disable the theme of package?

Thanks

**Comment by ueman** [comment]
Which version are you using? If you are using 0.3.0 you could try version [1.0.0-beta](https://pub.dev/packages/feedback/versions/1.0.0-beta) which hopefully fixed this issue.

**Comment by mukireus** [comment]
I am using 0.3.0, i will try. Thank you.

**Comment by ueman** [comment]
Does it fix your issue? 
If not could you provide some sample code to replicate the issue?

**Comment by mukireus** [comment]
Yes fixed. Thank you.
So how can i add custom language?

**Comment by ueman** [comment]
You have to implement your own Localization Delegate as seen in https://github.com/ueman/feedback/blob/master/lib/src/l18n/translation.dart and it to the BetterFeedback like here https://github.com/ueman/feedback#configuration . 
I would also really appreciate a PR if you are translating it anyways.

**Comment by ueman** [comment]
You also don't have to configure it yourself then.

**Comment by mukireus** [comment]
Thank you.
