### ISSUE TITLE
Dialog is rendered above the Feedback UI

### ISSUE THREAD

**Issue by quoc-huynh-cosee** [ueman/feedback#233]
### Version

2.6.0

### Library

feedback

### Flutter channel

stable

### Flutter version

 3.10.6

### Platform

Android

### Details

If I open the Feedback UI, then select the navigate button, and then opening a Dialog via a button, the Dialog is rendered above the Feedback UI, so that I can't interact with the Feedback UI anymore.

### Steps to reproduce

- Open Feedback UI
- Select navigate
- Open a Dialog

**Comment by ueman** [comment]
Where are you adding the better feedback widget? Can you share a snippet of that code?

**Comment by quoc-huynh-cosee** [comment]
I added the BetterFeedback Widget above the MaterialApp.
Here is a small example:
```dart
import 'package:feedback/feedback.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return BetterFeedback(
      child: MaterialApp(
        home: Builder(
          builder: (context) => Scaffold(
            appBar: AppBar(),
            body: Center(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  TextButton(
                    onPressed: () => BetterFeedback.of(context)
                        .show((feedback) => print(feedback)),
                    child: Text('FEEDBACK'),
                  ),
                  TextButton(
                    onPressed: () => showDialog(
                      context: context,
                      builder: (context) => AlertDialog(
                        title: Text('My Dialog'),
                        actions: [
                          TextButton(
                            onPressed: () => Navigator.pop(context),
                            child: Text('OK'),
                          ),
                        ],
                      ),
                    ),
                    child: Text('DIALOG'),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```

**Comment by quoc-huynh-cosee** [comment]
This is how it would look
![Uploading Bildschirmfoto 2023-08-01 um 09.55.45.png…]()

**Comment by Bungeefan** [comment]
Hi, did you try using [`showDialog(useRootNavigator: false, ...)`](https://api.flutter.dev/flutter/material/showDialog.html)?

**Comment by quoc-huynh-cosee** [comment]
@Bungeefan Nice, this is working. @ueman maybe we should add this to the README?

**Comment by ueman** [comment]
Feel free to create a PR and add it to the readme :)

**Comment by quoc-huynh-cosee** [comment]
@ueman Can you give me write permissions?

**Comment by ueman** [comment]
You don't need write permissions. You can fork the repo and then create a PR
