### ISSUE TITLE
Allow control on DraggableSheet

### ISSUE THREAD

**Issue by apomalyn** [ueman/feedback#238]
**Is your feature request related to a problem? Please describe.**

As a developer, I would like to have control of the DraggableSheet used when `sheetIsDraggable` is true.
In my specific case, I have a form with multiple fields on it, so I want to expand the sheet to fill the screen when the user focus on the form.

**Describe the solution you'd like**

Pass the `DraggableSheetController` or `BetterFeedback.of(context).expandSheet()`.

**Describe alternatives you've considered**

Something similar was proposed in the PR #88

**Comment by ueman** [comment]
Should be closed via https://github.com/ueman/feedback/pull/239
