### ISSUE TITLE
Use the Theme data to style the 'Submit' button

### ISSUE THREAD

**Issue by dhurbhat** [ueman/feedback#245]
**Is your feature request related to a problem? Please describe.**
While Theme data is fine, the color of "Submit" button etc. is not updated.

**Describe the solution you'd like**
In `string_feedback.dart` would be nice if the following `style` was added to the `child: Text` widget.

```
            style: TextStyle(
              color: FeedbackTheme.of(context).activeFeedbackModeColor,
            ) ,
```

**Comment by ueman** [comment]
Hey, are you willing to contribute this as a PR?

**Comment by rohitbhoite** [comment]
https://github.com/ueman/feedback/pull/249
Added fix in above PR.
