### ISSUE TITLE
Tabbing broken in dialogs

### ISSUE THREAD

**Issue by ignatz** [ueman/feedback#253]
### Version

latest

### Library

feedback

### Flutter channel

stable

### Flutter version

3.13.9

### Platform

Web

### Details

When opening a dialog with inputs, tabbing doesn't work (i.e using the tab key to jump through inputs). Removing the BetterFeedback shell makes tabbing work as expected.

This may be related to #205 but :shru

### Steps to reproduce

Step1: open a dialog with input fields (buttons, text, ...)
Step2: press <tab>
Step3: nothing happens

**Comment by JesusHdez960717** [comment]
hi @ignatz, the PR (#293) that solves this bug  and the related issue (#205) is finally merged , if you want test it again with the latest version (3.1.0) to make sure and in case the bug is not reproduced any more, feel free to close this issue
