### ISSUE TITLE
Adding vídeo recording

### ISSUE THREAD

**Issue by shinayser** [ueman/feedback#265]
This package is an absolute pearl!

It would be awesome if it could record a video instead of just screenshots.

**Comment by ueman** [comment]
Due to how this works, it's unfortunately currently not technically feasible. But I agree that it would be awesome! I've experimented with this idea here: https://pub.dev/packages/screen_recorder But at this state it doesn't make sense to integrate it.

**Comment by shinayser** [comment]
THanks for the answer! I will take a look at that other repo :)
