### ISSUE TITLE
Cannot capture dialog

### ISSUE THREAD

**Issue by nhorsopheak** [ueman/feedback#266]
### Version

3.0.0

### Library

feedback

### Flutter channel

stable

### Flutter version

3.16.9

### Platform

iOS

### Details

![photo_2024-02-07 12 48 34](https://github.com/ueman/feedback/assets/52164658/a49a064a-23c1-4656-b65e-43c42ad484d0)

cannot capture dialog and cannot close dialog when i click yes or no button.

### Steps to reproduce

- when show dialog

**Comment by S-ecki** [comment]
Did you read this part of the docs: https://pub.dev/packages/feedback#-known-issues-and-limitations ?
