### ISSUE TITLE
     final image = await renderObject.toImage(pixelRatio: pixelRatio); issue

### ISSUE THREAD

**Issue by mg3994** [ueman/feedback#268]
### Version

latest

### Library

feedback

### Flutter channel

stable

### Flutter version

3.16.9

### Platform

Web

### Details

     final image = await renderObject.toImage(pixelRatio: pixelRatio); bug 

### Steps to reproduce

just write something with color and click submit

**Comment by ueman** [comment]
Based on what you're writing I have no clue what's broken or how to even reproduce it. Please provide more actionable details.

**Comment by mg3994** [comment]
nothing much , i am just saying that it works fine till we doesn't write anything with color , after writing with color , and on clicking on submit button in web version it crash

**Comment by ueman** [comment]
Can you provide a stacktrace? Which web renderer are you using?

**Comment by mg3994** [comment]
chrome

**Comment by ueman** [comment]
Chrome is not a web renderer. Taking screenshots is not supported using the HTML renderer, this already mentioned as a limitation in the readme. I tested again with the CanvasKit renderer and that works.
