### ISSUE TITLE
Update to intl@^0.19.0

### ISSUE THREAD

**Issue by ricardoboss** [ueman/feedback#278]
**Is your feature request related to a problem? Please describe.**
I want to use the latest version of [intl](https://pub.dev/packages/intl), which is currently `0.19.0` but `feedback` requires `0.18.1`.

**Describe the solution you'd like**
Ideally, `feedback` could just allow newer minor versions of `intl` in general. But the "minimum effort" solution would be to just bump the dependency to `0.19.0`.

**Describe alternatives you've considered**
I could downgrade to `intl@0.18.1`, but I'm not sure this will always be the case for everyone.

**Comment by ricardoboss** [comment]
Okay, `feedback` doesn't directly depend on `intl`. `flutter pub get` yields this message:

```
Resolving dependencies... 
Note: intl is pinned to version 0.18.1 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because no versions of feedback match >3.0.0 <4.0.0 and feedback 3.0.0 depends on flutter_localizations from sdk, feedback ^3.0.0 requires flutter_localizations from sdk.
And because every version of flutter_localizations from sdk depends on intl 0.18.1, feedback ^3.0.0 requires intl 0.18.1.
So, because <app> depends on both intl ^0.19.0 and feedback ^3.0.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on intl: flutter pub add intl:^0.18.1
```

**Comment by ricardoboss** [comment]
I guess you can't influence the constraints from the `flutter_localizations`...

**Comment by Mistic92** [comment]
I just encountered same issue.
