### ISSUE TITLE
Support sentry_flutter: 8.1.0

### ISSUE THREAD

**Issue by danielgomezrico** [ueman/feedback#305]
**Is your feature request related to a problem? Please describe.**
I tried updating my sentry dependency to 8.1.0 but it fails:

These are de versions:
```yaml
sentry_flutter: 8.1.0
feedback_sentry: 3.0.0
```

Error:
```console
Because sentry_flutter >=8.1.0 depends on sentry 8.1.0 and feedback_sentry 3.0.0 depends on sentry ^7.0.0, sentry_flutter >=8.1.0 is incompatible with feedback_sentry 3.0.0.
So, because drivers_app depends on both feedback_sentry 3.0.0 and sentry_flutter 8.1.0, version solving failed.
```

**Describe the solution you'd like**
Allow sentry flutter > 7

**Comment by ueman** [comment]
A fix has been merged already, I just haven't come around to release it. In the meantime you can just use a `dependency_override` since the changes aren't breaking.

**Comment by danielgomezrico** [comment]
Got it and thanks for answering
