### ISSUE TITLE
Upgrade to sentry_flutter 8.x

### ISSUE THREAD

**Issue by bizz84** [ueman/feedback#313]
**Is your feature request related to a problem? Please describe.**

`feedback_sentry 3.0.0` is incompatible with the latest `sentry_flutter >=8.3.0`: 

```
Because feedback_sentry 3.0.0 depends on sentry ^7.0.0 and sentry_flutter >=8.3.0 depends on sentry 8.3.0, feedback_sentry 3.0.0 is incompatible with sentry_flutter >=8.3.0.
```

**Describe the solution you'd like**

Update the package to be compatible with sentry_flutter >=8.x.

Btw, thanks for this super useful package! 🙏

**Comment by ueman** [comment]
For now, you can use a dependency override in your pubspec. It's API compatible

**Comment by ueman** [comment]
https://pub.dev/packages/feedback_sentry/changelog
