### ISSUE TITLE
Create a default darkmode theme

### ISSUE THREAD

**Issue by ueman** [ueman/feedback#38]
This library currently needs the user to implement a darkmode theme himself. 
The library should handle it itself and also change it depending on the OS

**Comment by apomalyn** [comment]
Do you mind if I take this one for Hacktoberfest? 😄

**Comment by ueman** [comment]
No, not at all. Feel free to work on it. Please be aware though, that I'm on vacation for the first half of October, so I may not be able to review it in time.
