### ISSUE TITLE
Demonstrate different feedback sharing ideas

### ISSUE THREAD

**Issue by ueman** [ueman/feedback#41]
The readme and example app should contain different examples or strategies on how the author can enable the user to share feedback.

A couple ideas:

- as interface for Sentrys User Feedback ( https://github.com/getsentry/sentry-dart/issues/215 )
- sharing via share dialog
- sharing via http upload
- create GitHub/GitLab issue
- upload to imgur or similar
- create Jira-Tickets or similar

**Comment by JamesCullum** [comment]
It would make sense to add demo code for a simple email sharing, like here: https://github.com/ueman/feedback/issues/42#issue-823526556

**Comment by ueman** [comment]
Yeah, I agree. Are you interested in contributing this via PR?

**Comment by JamesCullum** [comment]
Yes, will create a PR and add it to the example and README
