### ISSUE TITLE
Page layout problem

### ISSUE THREAD

**Issue by Aquarius-M** [ueman/feedback#47]
If the screen is small
Bottom sheetis too high and Block the upper part,Textfield is too high

**Version of the library**
1.0.1

**Comment by NephKis** [comment]
![Screenshot_20210321-183321](https://user-images.githubusercontent.com/47274897/111902266-95914900-8a77-11eb-80f3-bb6696e4ebec.png)

**Comment by ueman** [comment]
Hey, thanks for raising this.
What are the dimensions of the screen in pixels and inches? 
How would you expect it to work?

**Comment by NephKis** [comment]
This problem happened in 5.2 inches, 1920 x 1080 pixels.
I think you can hide bottom sheet first and pull it up as a button. In this way, the operation will be more convenient.The display will be larger.

**Comment by caseycrogers** [comment]
This should be addressed by #147  and #149.
