### ISSUE TITLE
Can't build and run on web

### ISSUE THREAD

**Issue by nmuegge** [ueman/feedback#50]
**Describe the bug**
Plugin seems like it is not compatible with web. Build and run on web fail with the provided error message even when null-safety disabled.

**Version of the library**
feedback-1.0.2

**To Reproduce**
Add feedback plugin to your flutter project and you will get the null error regarding the Locale parameter in the localization file.

**Expected behavior**
Should not throw error. Currently we can't even build the project. 

**Logs **

ERROR MESSAGE:
../../.pub-cache/hosted/pub.dartlang.org/feedback-1.0.2/lib/src/l18n/localization.dart:34:30: Error: The argument type 'Locale?' can't be assigned to the parameter type 'Locale' because 'Locale?' is nullable and 'Locale' isn't.
 - 'Locale' is from 'dart:ui'.
      locale: localeOverride ?? window.locale,

FLUTTER DOCTOR -V: 

[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-US)
    • Flutter version 2.0.3 at /Users/user/development/flutter
    • Framework revision 4d7946a68d (6 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90

• No issues found!

**Additional context**
Sadly, we can't even build the app with null safety enabled. Any response/reply is greatly appreciated! 

Thank you very much in advance!

**Comment by ueman** [comment]
Hey, thanks for raising this.
Are you interested in fixing this and opening a PR? I'm not a user of Flutter Web so if there are more issues I'm not aware of you could fix them too. I would be happy to guide you.

**Comment by nmuegge** [comment]
For sure! I will! I'll get back to you when I fixed it!

**Comment by ueman** [comment]
I think you just need to change this 
https://github.com/ueman/feedback/blob/0758e6d06fe4da8a4156dc86503f431cf3154352/lib/src/l18n/localization.dart#L34

to 
`locale: localeOverride ?? window.locale ?? const Locale('en', 'US'),`

**Comment by ueman** [comment]
This is now fixed in version 1.1.0
