### ISSUE TITLE
Enter-Button should dismiss keyboard

### ISSUE THREAD

**Issue by reju1021** [ueman/feedback#56]
Enhancement/Feature Request

Hi there,

first of all: Thank you very much for this amazing package! It's really easy and convenient to implement and looks great. However, I think it would improve the user experience if the keyboard dismisses on pressing 'Enter'. Otherwise the next thing I'd try to dismiss it would be tapping on the screen (which does not dismiss it either) and it took me a moment to realise that only pressing "Paint" would dismiss it. I think changing the pressing on 'Enter' behaviour would be a positive change for the user experience. I already changed it locally -> 'feedback_bottom_sheet.dart' line 75, add the one-liner: textInputAction: TextInputAction.done.

It might be also cool for people not wanting this behaviour, to just pass a value in the initial constructor (like dismissOnEnter property).

Best regards,

Julian

**Comment by ueman** [comment]
Hey, thanks for raising this. I think I agree with you and dismissing the keyboard on enter is probably the better default. Are you interested in doing a PR? It seems like you already changed it anyway. I would gladly guide you through it if you need any help.

**Comment by reju1021** [comment]
I've never done this before :D. I gave it a try and submitted a new pull request. I've build it locally and it works (could only test iOS so far.)

**Comment by ueman** [comment]
Yeah, no worries. We all gotta start somewhere. 
The changelog step failed because you didn't add an entry to it. 
It's not that bad and can be merged when all other steps are successful. 
I can take over frome here.
Thanks again 👍
