### ISSUE TITLE
The Color Theme For the Navigate/Draw Selector Is Confusing

### ISSUE THREAD

**Issue by caseycrogers** [ueman/feedback#75]
**Is your feature request related to a problem? Please describe.**
The "Navigate" and "Draw" selectors are confusing. When an option is selected, it is greyed out to indicate that that button is currently not active. This is confusing because many users might think greyed out means "not currently selected".

**Describe the solution you'd like**
I believe the convention in Material Design is to use `Theme.of(context).accentColor` to indicate that one option out of several is currently selected. As such, I suggest we make the selected text use the accent color and the currently selected text use the default dark color.

**Describe alternatives you've considered**
Expand `FeedbackTheme` to allow users to customize their active and inactive selection text styles.

**Comment by ueman** [comment]
Thanks for raising this. It does really make much sense to change it.
