### ISSUE TITLE
Allow Custom FeedbackBottomSheet

### ISSUE THREAD

**Issue by caseycrogers** [ueman/feedback#77]
**Is your feature request related to a problem? Please describe.**
I want to include a feedback form with things like a drop down where users specify what kind of feedback it is (bug report, feature suggestion, etc.).

**Describe the solution you'd like**
Note that I plan to make this as a PR in my fork of `BetterFeedback`, the following is my implementation plan. Let me know if you have any feedback!

1. Update `OnSubmit` to take in a type parameter `T`.
2. Add an optional `Widget Function(OnSubmit<T>)? getFeedback` argument to `BetterFeedback`.
3. Update `OnFeedBackCallBack` to take feedback of type `T` instead of `String`.

If `getFeedback` is null, Type `T` will be `String` and `BetterFeedback` will behave as it does now. If the user specifies a non-null `getFeedback` function, `FeedbackBottomSheet` will be built with their widget and type `T` will be determined by `getFeedback`.

This way, users can prompt for and return arbitrary data types/models using `BetterFeedback`.

**Comment by ueman** [comment]
This is now available on pub in beta:
https://pub.dev/packages/feedback/versions/2.0.0-beta.0
