### ISSUE TITLE
Expand the Bottom Feedback Sheet When Active

### ISSUE THREAD

**Issue by caseycrogers** [ueman/feedback#88]
**Is your feature request related to a problem? Please describe.**
The bottom feedback sheet takes up very little space so that it doesn't cover the screenshot UI. This is non-ideal when the user is trying to write their feedback-especially for custom multi-part `FeedbackBuilder`'s the user can see very little of the feedback form at a time and has to scroll a lot.

**Describe the solution you'd like**
When the bottom feedback sheet is active (eg if any of it's children currently have focus) it will slide upwards to cover up 90-100% of the screen. The user can slide on a visual nodule at the top to slide it back down, or use their system back button. They can also slide the nodule to expand the feedback sheet if it is currently not active.
See: [sliding up panel](https://pub.dev/packages/sliding_up_panel).

Depending on preference, we could use the above package or #rollOurOwn. I lean lightly towards the latter as this should be pretty simple to implement.

**Describe alternatives you've considered**

- Have a "next" button that transition to a new screen where the user provides input. I think this has slightly less preferable UX as it's not as fluid transitioning between taking a screenshot and writing feedback.

**Comment by ueman** [comment]
Some more alternatives:

- Use a [PageView](https://api.flutter.dev/flutter/widgets/PageView-class.html)
- Use Dialogs

A resizeable BottomSheet makes the most sense though, I guess.

If possible I would use the already available Flutter implementation for that.
It should expand if in focus and shrink if the user interacts with the app, eg. draws or navigates.

**Comment by ueman** [comment]
Closed by #149
