### ISSUE TITLE
Unable to delete text in MacOS desktop app

### ISSUE THREAD

**Issue by TyBarthel** [ueman/feedback#91]
**Describe the bug**
After typing some feedback, the delete key cannot be used to delete on MacOS desktop.

**Version of the library**
This is an issue in latest stable 1.2.2 as well as 2.0.0-beta

**Expected behavior**
Delete key should delete text.

```
void main() {
  runApp(
    BetterFeedback(
      mode: FeedbackMode.draw,
      theme: FeedbackThemeData(
        background: Color(0xFF747474),
        feedbackSheetColor: Colors.grey[50]!,
        drawColors: [
          Colors.red,
          Colors.green,
          Colors.blue,
          Colors.yellow,
        ],
      ),
      child: const ProviderScope(
        child: Shell(),
      ),
    ),
  );
}
```

```
[✓] Flutter (Channel master, 2.3.0-17.0.pre.98, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
    • Flutter version 2.3.0-17.0.pre.98 at /Users/tyler/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5c92c5f2c8 (10 days ago), 2021-05-27 16:44:03 -0400
    • Engine revision cd4ce935c4
    • Dart version 2.14.0 (build 2.14.0-153.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 91.0.4472.77
```

**Comment by ueman** [comment]
Thanks for raising this issue.

I see that you're using the Flutter master channel, have you tested that behavior on the stable channel?
This library only runs its tests against stable and beta, so running this package on master could very well be broken.

Does this happen on other platforms, too? 
Does it consistently happen after the same amount of deletes?

**Comment by TyBarthel** [comment]
Looks like it's an issue just on master.  I tried beta and stable and delete works fine.  It's a bit strange that all other text fields work properly with delete on master though so I'm not sure what to think about that.

On a side note, it would be nice to have the feedback area where the text is input to be extensible to take any type of widget so then it would allow for custom fields to be captured with any desired layout.  Either that or allow using the screenshot widget as a separate standalone option.

**Comment by ueman** [comment]
Well in that case I'm going to close this. If it happens in the next major stable version I'll reopen this issue. Thanks again for bringing it up. I hope you're enjoying this package so far.

**Comment by DragonSlayer88** [comment]
Id like to reopen this, i am using Flutter 2.8.1 stable channel and i cant backspace with this textfield. All other textfields are fine. Im using windows desktop.

**Comment by ueman** [comment]
This might be related to https://github.com/flutter/flutter/issues/90525

**Comment by DragonSlayer88** [comment]
I dont think it is. All of my other textfields works fine besides the one that is in this feedback page. And apparently they fixed this in an early stable release, I am using the stable channel updated to 2.8.1 so that issue should not exist anymore.
