### ISSUE TITLE
how to get screenshot in apple_map_flutter

### ISSUE THREAD

**Issue by shivamagarwal2097** [ueman/feedback#94]

**Comment by ueman** [comment]
There's no way to do this currently. It's a limitation of the Flutter Framework. So sadly I can't do anything about that 🙁
See this issue https://github.com/flutter/flutter/issues/25306 . Please thumbs up the issue, in order to get it fixed.

**Comment by shivamagarwal2097** [comment]
have  any idea about methd
like google_map_flutter integrate a function name take screenshot

**Comment by ueman** [comment]
You'll probably need to write native code for that. You should take a look here https://flutter.dev/community and try to ask there. Good look
